// Generated by https://quicktype.io

export interface Position {
    id:    number;
    title: string;
}// Generated by https://quicktype.io

export interface RemoveResponse {
    message: string;
}

